### PR TITLE
elm-upgrade to 0.19.

### PR DESCRIPTION
**Pull request by billstclair**
Bump version from 1.1.1 to 1.1.2.

Updated elm and elm-test versions in circle.yml.

Removed ci-elm-hack from circle.yml. I haven't tested running the tests with circleCI, but I ran them all by hand, including the long tests, which took a long time.

I tested with my updated sources for ktonon/elm-word copied into the src directory, and no reference to ktonon/elm-word in elm.json. I added a dependency on version 2.1.2 or greater before committing, so this won't work until the 0.19 upgrade of elm-word has been published.

### CODE REVIEW

**Comment by billstclair** [comment]
I have seen no evidence that you're even looking at GitHub any more, so unless I hear from you by next Monday, I'm going to publish your `elm-word` and `elm-crypto` packages as `billstclair/elm-word` and `billstclair/elm-crypto`, so I can upgrade `billstclair/elm-crypto-string`. I'd rather not, hence this long delay since I submitted my pull request in August, but I need them.

**Comment by billstclair** [comment]
I'm willing, but I'd prefer you keep them. I have a lot to keep up with already. Your choice.

**Comment by ktonon** [comment]
>I'm willing, but I'd prefer you keep them. I have a lot to keep up with already. Your choice.

@billstclair ok. Merged and published `elm-word` today. I will look at this one tomorrow 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ktonon** [comment]
Published: https://package.elm-lang.org/packages/ktonon/elm-crypto/latest/

**Pull request merged**
